import type { ImportRouteData } from "@/stores/projectStore";

export const demoProject: ImportRouteData = {
  name: "Pacific Rim Adventure",
  mapStyle: "standard",
  viewportRatio: "16:9",
  cityLabelLang: "en",
  cityLabelSize: 20,
  albumStyle: "japanese-minimal",
  albumCaptionsEnabled: false,
  photoStyle: "classic",
  photoFrameStyle: "borderless",
  photoAnimation: "scale",
  sceneTransition: "dissolve",
  moodColorsEnabled: true,
  chapterPinsEnabled: true,
  breadcrumbsEnabled: false,
  tripStatsEnabled: false,
  locations: [
    {
      name: "Seattle",
      nameLocal: "西雅图",
      coordinates: [-122.3321, 47.6062],
      chapterEmoji: "☕",
      chapterTitle: "Seattle",
      chapterDate: "Day 1",
    },
    {
      name: "Honolulu",
      nameLocal: "檀香山",
      coordinates: [-157.8583, 21.3069],
      chapterEmoji: "🌺",
      chapterTitle: "Honolulu",
      chapterDate: "Day 3",
      photos: [
        { url: "/demo-photos/honolulu-1.jpg", caption: "Waikiki Beach 🏖️" },
        { url: "/demo-photos/honolulu-2.jpg", caption: "Diamond Head at sunrise 🌅" },
      ],
      photoLayout: {
        mode: "auto",
        template: "collage",
        gap: 6,
        borderRadius: 12,
        photoStyle: "classic",
        enterAnimation: "scale",
        sceneTransition: "blur-dissolve",
        captionFontSize: 18,
      },
    },
    {
      name: "Tokyo",
      nameLocal: "东京",
      coordinates: [139.6917, 35.6895],
      chapterEmoji: "🗼",
      chapterTitle: "Tokyo",
      chapterDate: "Day 6–8",
      photos: [
        { url: "/demo-photos/tokyo-1.jpg", caption: "Neon streets of Shinjuku 🌆" },
        { url: "/demo-photos/tokyo-2.jpg", caption: "Shibuya crossing madness 🚶" },
        { url: "/demo-photos/tokyo-3.jpg", caption: "Tokyo Tower at dusk 🗼" },
      ],
      photoLayout: {
        mode: "auto",
        template: "collage",
        gap: 6,
        borderRadius: 10,
        photoStyle: "classic",
        enterAnimation: "scale",
        sceneTransition: "cut",
        captionFontSize: 15,
      },
    },
    {
      name: "Taoyuan",
      nameLocal: "桃园",
      coordinates: [121.2168, 24.9936],
      isWaypoint: true,
    },
    {
      name: "Taipei",
      nameLocal: "台北",
      coordinates: [121.5654, 25.033],
      chapterEmoji: "🏯",
      chapterTitle: "Taipei",
      chapterDate: "Day 9–11",
      photos: [
        { url: "/demo-photos/taipei-1.jpg", caption: "Taipei 101 🌃" },
        { url: "/demo-photos/taipei-2.jpg", caption: "Night market feast 🍜" },
      ],
      photoLayout: {
        mode: "auto",
        template: "rows",
        gap: 8,
        borderRadius: 10,
        photoStyle: "classic",
        enterAnimation: "slide",
        sceneTransition: "dissolve",
        captionFontSize: 16,
      },
    },
    {
      name: "Tainan",
      nameLocal: "台南",
      coordinates: [120.227, 22.9998],
      chapterEmoji: "🛕",
      chapterTitle: "Tainan",
      chapterDate: "Day 12",
      photos: [
        { url: "/demo-photos/tainan-1.jpg", caption: "Ancient temple 🕯️" },
        { url: "/demo-photos/tainan-2.jpg", caption: "Old street wandering 🏮" },
      ],
      photoLayout: {
        mode: "auto",
        template: "rows",
        gap: 8,
        borderRadius: 4,
        photoStyle: "classic",
        enterAnimation: "fade",
        sceneTransition: "wipe",
        captionFontFamily: "serif",
        captionFontSize: 15,
      },
    },
    {
      name: "Chiayi",
      nameLocal: "嘉义",
      coordinates: [120.4491, 23.48],
      isWaypoint: true,
    },
    {
      name: "Alishan",
      nameLocal: "阿里山",
      coordinates: [120.7, 23.51],
      chapterEmoji: "🌄",
      chapterTitle: "Alishan",
      chapterDate: "Day 13",
      photos: [
        { url: "/demo-photos/alishan-1.jpg", caption: "Sea of clouds at dawn 🌤️" },
        { url: "/demo-photos/alishan-2.jpg", caption: "Forest railway 🚂" },
      ],
      photoLayout: {
        mode: "auto",
        template: "hero",
        gap: 6,
        borderRadius: 12,
        photoStyle: "kenburns",
        enterAnimation: "fade",
        sceneTransition: "blur-dissolve",
        captionFontSize: 17,
      },
    },
    {
      name: "Chiayi",
      nameLocal: "嘉义",
      coordinates: [120.4491, 23.48],
      isWaypoint: true,
    },
    {
      name: "Taoyuan",
      nameLocal: "桃园",
      coordinates: [121.2168, 24.9936],
      isWaypoint: true,
    },
    {
      name: "Seoul",
      nameLocal: "首尔",
      coordinates: [126.978, 37.5665],
      isWaypoint: true,
    },
    {
      name: "Seattle",
      nameLocal: "西雅图",
      coordinates: [-122.3321, 47.6062],
      chapterEmoji: "🏠",
      chapterTitle: "Home",
    },
  ],
  segments: [
    { fromIndex: 0, toIndex: 1, transportMode: "flight" },
    { fromIndex: 1, toIndex: 2, transportMode: "flight" },
    { fromIndex: 2, toIndex: 3, transportMode: "flight" },
    { fromIndex: 3, toIndex: 4, transportMode: "train" },
    { fromIndex: 4, toIndex: 5, transportMode: "train" },
    { fromIndex: 5, toIndex: 6, transportMode: "train" },
    { fromIndex: 6, toIndex: 7, transportMode: "train" },
    { fromIndex: 7, toIndex: 8, transportMode: "car" },
    { fromIndex: 8, toIndex: 9, transportMode: "train" },
    { fromIndex: 9, toIndex: 10, transportMode: "flight" },
    { fromIndex: 10, toIndex: 11, transportMode: "flight" },
  ],
};
